### ISSUE TITLE
Can't select target app sometimes

### ISSUE THREAD

**Issue by dotmagic** [arpruss/sendreduced#3]
Since I'm updated my Galaxy S5 with Marshmallow i can't select the target app anymore. Every time i choose to share a picture sendreduced don't ask me for target app and just open straight the last used app (Skype, Facebook Messenger).

I can reproduce this on my Gakaxy Tab S2 with Marshmallow.

**Comment by mr-gosh** [comment]
I have the same problem when i once selected the "save" / "remeber" checkbox.
I didn't find a way of purging this decission. None of these worked:
http://android.stackexchange.com/questions/42057/how-do-you-clear-share-actions-bound-to-copy-to-clipboard

**Comment by iakiakiak** [comment]
Same here with SGS7. Tried to delete all app data and also reinstalled without any luck.

**Comment by dotmagic** [comment]
It's fixed with v0.16. But that version is only in Google Play and not f-droid
